apiVersion: api-management.sensedia.com/v1
kind: Plan
spec:
  name: '[DEV][CLI] Default Plan'
  apiRef:
    name: cli-swapi-poc
    version: 1.0.0
  default: true
  flows:
  - context:
      revision: all
      resourceRef:
        name: all
      operationRef:
        method: all
        path: /
    requestInterceptors:
    - restrictAccess:
        environmentRefs:
        - name: "[DEV] Sensedia CLI"
        type: ALLOW_LIST
