apiVersion: api-management.sensedia.com/v1
kind: Plan
spec:
  name: '[HML][CLI] Default Plan'
  apiRef:
    version: 1.0.0
    name: cli-swapi-poc
  default: false
  flows:
  - context:
      revision: all
      resourceRef:
        name: all
      operationRef:
        method: all
        path: /
    requestInterceptors:
    - restrictAccess:
        environmentRefs:
        - name: "[HML] Sensedia CLI"
        - name: "[HML] Sensedia CLI Test"
        type: ALLOW_LIST
