apiVersion: api-management.sensedia.com/v1
kind: RestAPI
spec:
  # Campos de identificação
  name: cli-swapi-poc
  version: 1.0.0
  basePath: /star-wars/v1
  stageRef:
    name: Draft
  description: API Sample
  resources:
  - name: /people
    operations:
    - method: GET
      path: /random
  flow:
    destination: $sw-url
    requestInterceptors:
    - oauth:
        allowedGrantTypes: ["ClientCredentials"]
    - log:
        encryptContent: false
        encryptParams: false
    - spikeArrest:
        interval: Minute
        limit: 10
    responseInterceptors:
    - log:
        encryptContent: false
        encryptParams: false
