apiVersion: api-management.sensedia.com/v1
kind: Plan
spec:
  name: '[HML][Sample] Default Plan'
  apiRef:
    version: 2.0.0
    name: cli-pokeapi-poc-sample
  default: true
  flows:
  - context:
      revision: all
      resourceRef:
        name: all
      operationRef:
        method: all
        path: /
    requestInterceptors:
    - restrictAccess:
        environmentRefs:
        - name: "[HML] Sensedia CLI Sample"
        type: ALLOW_LIST
