apiVersion: api-management.sensedia.com/v1
kind: Plan
spec:
  name: '[HML] API Ops Days Plan Sample'
  apiRef:
    version: v1
    name: APIOps API Days API Sample
  default: true
  flows:
  - context:
      revision: all
      resourceRef:
        name: all
      operationRef:
        method: all
        path: /
    requestInterceptors:
    - restrictAccess:
        environmentRefs:
        - name: "[HML] APIOps API Days Env Sample"
        type: ALLOW_LIST
