apiVersion: api-management.sensedia.com/v1
kind: RestAPI
spec:
  version: v1
  name: APIOps API Days API Sample
  basePath: /api-days/v1
  description: APIOps API Days API Sample
  stageRef:
    name: Draft
  flow:
    destination: $destination-url
    requestInterceptors:
    - oauth:
        allowedGrantTypes: ["ClientCredentials"]
    - log:
        encryptContent: false
        encryptParams: false
    - spikeArrest:
        interval: Second
        limit: 10
    responseInterceptors:
    - log:
        encryptContent: false
        encryptParams: false
